import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'node:fs'
import os from 'node:os'

// Automatically find local IP and write to src/ip-config.js
function getLocalIP() {
  const interfaces = os.networkInterfaces();
  for (const name of Object.keys(interfaces)) {
    for (const iface of interfaces[name]) {
      if (iface.family === 'IPv4' && !iface.internal) {
        return iface.address;
      }
    }
  }
  return '127.0.0.1';
}

try {
  const localIP = getLocalIP();
  const content = `// This file is auto-generated by vite.config.js. Do not edit manually.\nexport const LOCAL_IP = "${localIP}";\n`;
  fs.writeFileSync('./src/ip-config.js', content, 'utf-8');
  console.log(`[Vite Config] Dynamic local IP detected and saved: ${localIP}`);
} catch (e) {
  console.error('[Vite Config] Failed to save local IP:', e);
}

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5000,
    host: true
  }
})
